import Vangabond from "../../Assets/ProductImages/HomeProductImages/1/Vangabond-1.jpg";
import AttackonTitan from "../../Assets/ProductImages/HomeProductImages/2/Attack-On-Titan-1.jpg";
import Berserk from "../../Assets/ProductImages/HomeProductImages/3/Berserk-1.jpg";
import BlueLock from "../../Assets/ProductImages/HomeProductImages/4/Blue-Lock-1.jpg";
import DeathNote from "../../Assets/ProductImages/HomeProductImages/5/Death-Note-1.jpg";

let HomePage = [
  {
    id: 1,
    image: Vangabond,
    name: "Vangaobond Volume 1",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 2,
    image: AttackonTitan,
    name: "Attack On Titan Volume 1",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 3,
    image: Berserk,
    name: "Berserk Volume 1 ",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 4,
    image: BlueLock,
    name: "Blue Lock Volume 1",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 5,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 6,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 7,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 8,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 9,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 10,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 11,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 12,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 13,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 14,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 15,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 16,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 17,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 18,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 19,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 20,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 21,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 22,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 23,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 24,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 25,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 26,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 27,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
  {
    id: 28,
    image: DeathNote,
    name: "Death Note",
    brand: "Manga",
    newprice: "Rs. 300",
    oldprice: "Rs. 500",
  },
];

export default HomePage;
